import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Feature from '@/components/feature';
import Row from '@/components/row';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Row>
          <Feature title="Lista della spesa"
            icon="bi bi-collection-fill"
            description="Esercizio su utilizzo di JSX e React Component" link="/shopping" />
          <Feature title="TODO List"
            icon='bi bi-card-checklist'
            description="Esercizio JSX sull'utilizzo di props e state"
            link="/todo" />
          <Feature title="Tic-Tac-Toe"
            icon='bi bi-dpad'
            description="Esercizio" link="/tris" />
          <Feature title="Animation Sample"
            icon='bi bi-camera-video'
            description="Esercizio su animazioni"
            link="/animation" />
        </Row>
      </main>
    </>
  )
}
